### ISSUE TITLE
Failed on https://ipaddress.com/website/githut.info

### ISSUE THREAD

**Issue by huangxiangyao** [myvas/ipfix#1]
ipfix 6.0.4
```
System.ApplicationException: Sorry, I cannot get a result. Please do me a favor to add an issue on https://github.com/myvas/ipfix, titled with 'Failed on https://ipaddress.com/website/githut.info'.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Myvas.Tools.IpFix.IpAddressFetcher.RetrieveIpAddress(String dns)
   --- End of inner exception stack trace ---
   at Myvas.Tools.IpFix.IpAddressFetcher.RetrieveIpAddress(String dns)
   at Myvas.Tools.IpFix.Program.Fix(String dns)
```

**Comment by huangxiangyao** [comment]
alt to nslookup.io#USA
See version 6.0.5
